before_install:
   - sudo apt-get update -qq
   - sudo apt-get install avahi-daemon libavahi-compat-libdnssd-dev
   - wget https://github.com/rebar/rebar/wiki/rebar
   - wget https://s3.amazonaws.com/rebar3/rebar3
   - chmod u+x ./rebar
   - chmod u+x ./rebar3
language: elixir
elixir:
    - 1.0.5
    - 1.1.0
    - 1.1.1
otp_release:
   - 17.5
   - 18.0
script: 
    - mix deps.get
    - mix compile
    - rm -Rf deps _build
    - ./rebar3 update
    - ./rebar3 compile
    - rm -Rf _build
    - ./rebar get-deps
    - ./rebar compile 
    - ./rebar ct skip_deps=true
after_failure: "cat logs/raw.log"
